version: '3'

services:
  terminal:
    build: .
    container_name: terminal
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_ENABLE_TRACKING=${ENABLE_TRACKING}
      - NEXT_PUBLIC_TRACKING_URL=${TRACKING_URL}
      - NEXT_PUBLIC_TRACKING_SITE_ID=${TRACKING_SITE_ID}
      - VIRTUAL_HOST=${VHOST}
      - LETSENCRYPT_HOST=${VHOST}
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${VHOST}:${VHOST_PORT}"]
      interval: 200s
      timeout: 200s
      retries: 5
      
  nginx:
      container_name: nginx
      image: nginxproxy/nginx-proxy
      restart: unless-stopped
      ports:
          - 80:80
          - 443:443
      volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /var/docker/nginx/html:/usr/share/nginx/html
          - /var/docker/nginx/certs:/etc/nginx/certs
          - /var/docker/nginx/vhost:/etc/nginx/vhost.d
      logging:
          options:
              max-size: "10m"
              max-file: "3"
  
  letsencrypt-companion:
      container_name: letsencrypt-companion
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: unless-stopped
      volumes_from:
          - nginx
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/docker/nginx/acme:/etc/acme.sh
      environment:
          DEFAULT_EMAIL: ${SSL_EMAIL}
